// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netty/MsgHeader.proto

package com.abin.lee.netty.model.proto;

public final class MsgHeaderProto {
  private MsgHeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.MsgHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string query = 1 [default = "abin"];</code>
     */
    boolean hasQuery();
    /**
     * <code>required string query = 1 [default = "abin"];</code>
     */
    String getQuery();
    /**
     * <code>required string query = 1 [default = "abin"];</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>optional int32 pageNum = 2 [default = 1];</code>
     */
    boolean hasPageNum();
    /**
     * <code>optional int32 pageNum = 2 [default = 1];</code>
     */
    int getPageNum();

    /**
     * <code>optional int32 pageSize = 3 [default = 10];</code>
     */
    boolean hasPageSize();
    /**
     * <code>optional int32 pageSize = 3 [default = 10];</code>
     */
    int getPageSize();

    /**
     * <code>required int64 userId = 4 [default = 0];</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 4 [default = 0];</code>
     */
    long getUserId();

    /**
     * <code>required string userName = 5 [default = "NoKnown"];</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 5 [default = "NoKnown"];</code>
     */
    String getUserName();
    /**
     * <code>required string userName = 5 [default = "NoKnown"];</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>required string passWord = 6 [default = "NoKnown"];</code>
     */
    boolean hasPassWord();
    /**
     * <code>required string passWord = 6 [default = "NoKnown"];</code>
     */
    String getPassWord();
    /**
     * <code>required string passWord = 6 [default = "NoKnown"];</code>
     */
    com.google.protobuf.ByteString
        getPassWordBytes();

    /**
     * <code>required int32 bodyLength = 7 [default = 0];</code>
     */
    boolean hasBodyLength();
    /**
     * <code>required int32 bodyLength = 7 [default = 0];</code>
     */
    int getBodyLength();

    /**
     * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
     */
    MsgHeader.MessageType getMessageType();

    /**
     * <code>repeated string address = 9;</code>
     */
    com.google.protobuf.ProtocolStringList
        getAddressList();
    /**
     * <code>repeated string address = 9;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated string address = 9;</code>
     */
    String getAddress(int index);
    /**
     * <code>repeated string address = 9;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes(int index);
  }
  /**
   * Protobuf type {@code netty.MsgHeader}
   */
  public  static final class MsgHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netty.MsgHeader)
      MsgHeaderOrBuilder {
    // Use MsgHeader.newBuilder() to construct.
    private MsgHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MsgHeader() {
      query_ = "abin";
      pageNum_ = 1;
      pageSize_ = 10;
      userId_ = 0L;
      userName_ = "NoKnown";
      passWord_ = "NoKnown";
      bodyLength_ = 0;
      messageType_ = 4;
      address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              query_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageSize_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              userId_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              userName_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              passWord_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              bodyLength_ = input.readInt32();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              MessageType value = MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                messageType_ = rawValue;
              }
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                address_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000100;
              }
              address_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          address_ = address_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgHeaderProto.internal_static_netty_MsgHeader_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgHeaderProto.internal_static_netty_MsgHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgHeader.class, Builder.class);
    }

    /**
     * Protobuf enum {@code netty.MsgHeader.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WEB = 1;</code>
       */
      WEB(0, 1),
      /**
       * <code>ANDROID = 2;</code>
       */
      ANDROID(1, 2),
      /**
       * <code>IOS = 3;</code>
       */
      IOS(2, 3),
      /**
       * <code>PLATFORM = 4;</code>
       */
      PLATFORM(3, 4),
      ;

      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>ANDROID = 2;</code>
       */
      public static final int ANDROID_VALUE = 2;
      /**
       * <code>IOS = 3;</code>
       */
      public static final int IOS_VALUE = 3;
      /**
       * <code>PLATFORM = 4;</code>
       */
      public static final int PLATFORM_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return WEB;
          case 2: return ANDROID;
          case 3: return IOS;
          case 4: return PLATFORM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MsgHeader.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netty.MsgHeader.MessageType)
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile Object query_;
    /**
     * <code>required string query = 1 [default = "abin"];</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string query = 1 [default = "abin"];</code>
     */
    public String getQuery() {
      Object ref = query_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string query = 1 [default = "abin"];</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGENUM_FIELD_NUMBER = 2;
    private int pageNum_;
    /**
     * <code>optional int32 pageNum = 2 [default = 1];</code>
     */
    public boolean hasPageNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 pageNum = 2 [default = 1];</code>
     */
    public int getPageNum() {
      return pageNum_;
    }

    public static final int PAGESIZE_FIELD_NUMBER = 3;
    private int pageSize_;
    /**
     * <code>optional int32 pageSize = 3 [default = 10];</code>
     */
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 pageSize = 3 [default = 10];</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private long userId_;
    /**
     * <code>required int64 userId = 4 [default = 0];</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 userId = 4 [default = 0];</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private volatile Object userName_;
    /**
     * <code>required string userName = 5 [default = "NoKnown"];</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string userName = 5 [default = "NoKnown"];</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 5 [default = "NoKnown"];</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 6;
    private volatile Object passWord_;
    /**
     * <code>required string passWord = 6 [default = "NoKnown"];</code>
     */
    public boolean hasPassWord() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string passWord = 6 [default = "NoKnown"];</code>
     */
    public String getPassWord() {
      Object ref = passWord_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passWord_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string passWord = 6 [default = "NoKnown"];</code>
     */
    public com.google.protobuf.ByteString
        getPassWordBytes() {
      Object ref = passWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODYLENGTH_FIELD_NUMBER = 7;
    private int bodyLength_;
    /**
     * <code>required int32 bodyLength = 7 [default = 0];</code>
     */
    public boolean hasBodyLength() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 bodyLength = 7 [default = 0];</code>
     */
    public int getBodyLength() {
      return bodyLength_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 8;
    private int messageType_;
    /**
     * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
     */
    public MessageType getMessageType() {
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.PLATFORM : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList address_;
    /**
     * <code>repeated string address = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      return address_;
    }
    /**
     * <code>repeated string address = 9;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated string address = 9;</code>
     */
    public String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated string address = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassWord()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBodyLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pageSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, userId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, userName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, passWord_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, bodyLength_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, messageType_);
      }
      for (int i = 0; i < address_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, address_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, userId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, userName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, passWord_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, bodyLength_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, messageType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += computeStringSizeNoTag(address_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static MsgHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MsgHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MsgHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MsgHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MsgHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MsgHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.MsgHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.MsgHeader)
        MsgHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgHeaderProto.internal_static_netty_MsgHeader_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgHeaderProto.internal_static_netty_MsgHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgHeader.class, Builder.class);
      }

      // Construct using com.abin.lee.netty.model.proto.MsgHeaderProto.MsgHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        query_ = "abin";
        bitField0_ = (bitField0_ & ~0x00000001);
        pageNum_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 10;
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        userName_ = "NoKnown";
        bitField0_ = (bitField0_ & ~0x00000010);
        passWord_ = "NoKnown";
        bitField0_ = (bitField0_ & ~0x00000020);
        bodyLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        messageType_ = 4;
        bitField0_ = (bitField0_ & ~0x00000080);
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgHeaderProto.internal_static_netty_MsgHeader_descriptor;
      }

      public MsgHeader getDefaultInstanceForType() {
        return MsgHeader.getDefaultInstance();
      }

      public MsgHeader build() {
        MsgHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MsgHeader buildPartial() {
        MsgHeader result = new MsgHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.query_ = query_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageNum_ = pageNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pageSize_ = pageSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.passWord_ = passWord_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bodyLength_ = bodyLength_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.messageType_ = messageType_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          address_ = address_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgHeader) {
          return mergeFrom((MsgHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgHeader other) {
        if (other == MsgHeader.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          bitField0_ |= 0x00000001;
          query_ = other.query_;
          onChanged();
        }
        if (other.hasPageNum()) {
          setPageNum(other.getPageNum());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000010;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassWord()) {
          bitField0_ |= 0x00000020;
          passWord_ = other.passWord_;
          onChanged();
        }
        if (other.hasBodyLength()) {
          setBodyLength(other.getBodyLength());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQuery()) {
          return false;
        }
        if (!hasUserId()) {
          return false;
        }
        if (!hasUserName()) {
          return false;
        }
        if (!hasPassWord()) {
          return false;
        }
        if (!hasBodyLength()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object query_ = "abin";
      /**
       * <code>required string query = 1 [default = "abin"];</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string query = 1 [default = "abin"];</code>
       */
      public String getQuery() {
        Object ref = query_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            query_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string query = 1 [default = "abin"];</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string query = 1 [default = "abin"];</code>
       */
      public Builder setQuery(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1 [default = "abin"];</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1 [default = "abin"];</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }

      private int pageNum_ = 1;
      /**
       * <code>optional int32 pageNum = 2 [default = 1];</code>
       */
      public boolean hasPageNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 pageNum = 2 [default = 1];</code>
       */
      public int getPageNum() {
        return pageNum_;
      }
      /**
       * <code>optional int32 pageNum = 2 [default = 1];</code>
       */
      public Builder setPageNum(int value) {
        bitField0_ |= 0x00000002;
        pageNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageNum = 2 [default = 1];</code>
       */
      public Builder clearPageNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNum_ = 1;
        onChanged();
        return this;
      }

      private int pageSize_ = 10;
      /**
       * <code>optional int32 pageSize = 3 [default = 10];</code>
       */
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 pageSize = 3 [default = 10];</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>optional int32 pageSize = 3 [default = 10];</code>
       */
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000004;
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pageSize = 3 [default = 10];</code>
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageSize_ = 10;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>required int64 userId = 4 [default = 0];</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 userId = 4 [default = 0];</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 4 [default = 0];</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 4 [default = 0];</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private Object userName_ = "NoKnown";
      /**
       * <code>required string userName = 5 [default = "NoKnown"];</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string userName = 5 [default = "NoKnown"];</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string userName = 5 [default = "NoKnown"];</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 5 [default = "NoKnown"];</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 5 [default = "NoKnown"];</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 5 [default = "NoKnown"];</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }

      private Object passWord_ = "NoKnown";
      /**
       * <code>required string passWord = 6 [default = "NoKnown"];</code>
       */
      public boolean hasPassWord() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string passWord = 6 [default = "NoKnown"];</code>
       */
      public String getPassWord() {
        Object ref = passWord_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            passWord_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string passWord = 6 [default = "NoKnown"];</code>
       */
      public com.google.protobuf.ByteString
          getPassWordBytes() {
        Object ref = passWord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string passWord = 6 [default = "NoKnown"];</code>
       */
      public Builder setPassWord(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        passWord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string passWord = 6 [default = "NoKnown"];</code>
       */
      public Builder clearPassWord() {
        bitField0_ = (bitField0_ & ~0x00000020);
        passWord_ = getDefaultInstance().getPassWord();
        onChanged();
        return this;
      }
      /**
       * <code>required string passWord = 6 [default = "NoKnown"];</code>
       */
      public Builder setPassWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        passWord_ = value;
        onChanged();
        return this;
      }

      private int bodyLength_ ;
      /**
       * <code>required int32 bodyLength = 7 [default = 0];</code>
       */
      public boolean hasBodyLength() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 bodyLength = 7 [default = 0];</code>
       */
      public int getBodyLength() {
        return bodyLength_;
      }
      /**
       * <code>required int32 bodyLength = 7 [default = 0];</code>
       */
      public Builder setBodyLength(int value) {
        bitField0_ |= 0x00000040;
        bodyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bodyLength = 7 [default = 0];</code>
       */
      public Builder clearBodyLength() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bodyLength_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ = 4;
      /**
       * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
       */
      public MessageType getMessageType() {
        MessageType result = MessageType.valueOf(messageType_);
        return result == null ? MessageType.PLATFORM : result;
      }
      /**
       * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
       */
      public Builder setMessageType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .netty.MsgHeader.MessageType messageType = 8 [default = PLATFORM];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        messageType_ = 4;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          address_ = new com.google.protobuf.LazyStringArrayList(address_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressList() {
        return address_.getUnmodifiableView();
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public String getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes(int index) {
        return address_.getByteString(index);
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public Builder setAddress(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public Builder addAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public Builder addAllAddress(
          Iterable<String> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public Builder clearAddress() {
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 9;</code>
       */
      public Builder addAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.MsgHeader)
    }

    // @@protoc_insertion_point(class_scope:netty.MsgHeader)
    private static final MsgHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgHeader();
    }

    public static MsgHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MsgHeader>
        PARSER = new com.google.protobuf.AbstractParser<MsgHeader>() {
      public MsgHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MsgHeader(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MsgHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MsgHeader> getParserForType() {
      return PARSER;
    }

    public MsgHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_MsgHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_MsgHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025netty/MsgHeader.proto\022\005netty\"\264\002\n\tMsgHe" +
      "ader\022\023\n\005query\030\001 \002(\t:\004abin\022\022\n\007pageNum\030\002 \001" +
      "(\005:\0011\022\024\n\010pageSize\030\003 \001(\005:\00210\022\021\n\006userId\030\004 " +
      "\002(\003:\0010\022\031\n\010userName\030\005 \002(\t:\007NoKnown\022\031\n\010pas" +
      "sWord\030\006 \002(\t:\007NoKnown\022\025\n\nbodyLength\030\007 \002(\005" +
      ":\0010\022;\n\013messageType\030\010 \001(\0162\034.netty.MsgHead" +
      "er.MessageType:\010PLATFORM\022\017\n\007address\030\t \003(" +
      "\t\":\n\013MessageType\022\007\n\003WEB\020\001\022\013\n\007ANDROID\020\002\022\007" +
      "\n\003IOS\020\003\022\014\n\010PLATFORM\020\004B0\n\036com.abin.lee.ne" +
      "tty.model.protoB\016MsgHeaderProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_MsgHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_MsgHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netty_MsgHeader_descriptor,
        new String[] { "Query", "PageNum", "PageSize", "UserId", "UserName", "PassWord", "BodyLength", "MessageType", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
